version: '3.3'

services:
  telegram_dev:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 4321
    env_file:
      - ./.env_local_dev
    networks:
      - host

networks:
  host:
    external: true
      name: host
